# Generated by Django 5.2.1 on 2025-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('valor_unitario', models.IntegerField()),
                ('categoria', models.CharField(choices=[('Tecnologia', 'Tecnologia'), ('Moda', 'Moda'), ('VideoJuegos', 'Videojuegos'), ('Sin Categoria', 'Na')], default='Sin Categoria', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
